name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (from one secret)
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          PASSWORD=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 2)
          echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          docker build -t "$USERNAME/my-app:latest" .

      - name: Push Docker image
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          docker push "$USERNAME/my-app:latest"
