name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          PASSWORD=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 2)
          echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          docker build -t "$USERNAME/my-app:latest" .

      - name: Push Docker image
        run: |
          USERNAME=$(echo "${{ secrets.DOCKERHUB_CREDENTIAL }}" | cut -d ':' -f 1)
          docker push "$USERNAME/my-app:latest"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
            docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
