name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub with single secret
        run: |
          echo "${{ secrets.DOCKERHUB }}" | docker login -u "$(echo "${{ secrets.DOCKERHUB }}" | cut -d':' -f1)" --password-stdin

      - name: Build Docker Image
        run: |
          curl -o .env https://your-env-source.com/env-file
          docker build -t "$(echo "${{ secrets.DOCKERHUB }}" | cut -d':' -f1)/my-app:latest" .

      - name: Push Docker Image
        run: |
          docker push "$(echo "${{ secrets.DOCKERHUB }}" | cut -d':' -f1)/my-app:latest"
